2021-03-10 09:53:07,810 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 09:53:07] "[33mGET / HTTP/1.1[0m" 404 -
2021-03-10 10:03:02,620 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 10:03:02] "[37mGET /api/v1/get_audio_files?audioFileType=podcast HTTP/1.1[0m" 200 -
2021-03-10 11:16:18,381 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 11:16:18] "[37mPOST /api/v1/create HTTP/1.1[0m" 200 -
2021-03-10 11:17:52,330 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:19:37,387 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:21:53,368 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:22:26,740 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:22:47,998 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:23:09,192 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 11:23:09] "[37mPOST /api/v1/create HTTP/1.1[0m" 200 -
2021-03-10 11:26:21,019 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 11:26:21,413 INFO werkzeug:  * Restarting with stat
2021-03-10 11:26:51,133 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 11:26:51,454 INFO werkzeug:  * Restarting with stat
2021-03-10 11:40:33,492 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:41:09,061 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 11:41:09,370 INFO werkzeug:  * Restarting with stat
2021-03-10 11:41:36,023 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 11:41:36,362 INFO werkzeug:  * Restarting with stat
2021-03-10 11:41:38,623 ERROR api: Exception on /api/v1/create [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 11:42:01,225 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 11:42:01] "[35m[1mPOST /api/v1/create HTTP/1.1[0m" 500 -
2021-03-10 11:43:05,018 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 11:43:23,685 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 12:16:27,561 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 12:36:00,868 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 12:36:18,819 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 12:36:43,700 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 12:36:43] "[37mPOST /api/v1/create HTTP/1.1[0m" 200 -
2021-03-10 12:36:51,998 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 12:36:51] "[31m[1mPOST /api/v1/create HTTP/1.1[0m" 400 -
2021-03-10 12:37:40,502 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 12:39:11,285 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 12:39:11,651 INFO werkzeug:  * Restarting with stat
2021-03-10 12:39:17,030 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 12:39:17,541 INFO werkzeug:  * Restarting with stat
2021-03-10 12:39:23,906 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 12:39:24,411 INFO werkzeug:  * Restarting with stat
2021-03-10 12:39:35,826 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 12:39:36,300 INFO werkzeug:  * Restarting with stat
2021-03-10 12:40:29,270 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/database/AudioSchema.py', reloading
2021-03-10 12:40:29,474 INFO werkzeug:  * Restarting with stat
2021-03-10 12:40:31,790 INFO werkzeug:  * Detected change in '/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/create.py', reloading
2021-03-10 12:40:31,873 INFO werkzeug:  * Restarting with stat
2021-03-10 12:49:23,116 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:00:08,039 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:01:38,651 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:02:10,267 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:07:04,432 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:07:23,968 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:07:24,510 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:07:50,961 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:07:51,450 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:08:09,976 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:09] "[31m[1mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6045409e64d7463f32c49a65 HTTP/1.1[0m" 400 -
2021-03-10 13:08:18,924 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:18] "[31m[1mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6045409e64d7463f32c49a65 HTTP/1.1[0m" 400 -
2021-03-10 13:08:22,620 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:22] "[37mPOST /api/v1/update_audio_file?audioFileType=audiobook&audioFileID=6046fb47278e97c72a6633b7 HTTP/1.1[0m" 200 -
2021-03-10 13:08:29,391 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:29] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046f26a4b09a4463e43742e HTTP/1.1[0m" 200 -
2021-03-10 13:08:36,119 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:36] "[31m[1mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6045409e64d7463f32c49a65 HTTP/1.1[0m" 400 -
2021-03-10 13:08:52,656 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:08:52] "[37mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6046fc3b278e97c72a6633b8 HTTP/1.1[0m" 200 -
2021-03-10 13:09:02,656 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:09:03,181 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:09:52,172 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:09:52,687 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:10:11,064 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:10:11,553 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:11:12,460 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:11:12,976 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:11:23,855 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:11:23] "[37mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6046fc3b278e97c72a6633b8 HTTP/1.1[0m" 200 -
2021-03-10 13:11:55,666 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:11:56,153 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:13:30,762 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:13:31,266 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:13:31,500 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:13:55,516 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:13:55] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 200 -
2021-03-10 13:14:33,868 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:14:34,354 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:14:34,583 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:15:12,694 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:15:13,184 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:15:13,414 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:16:33,080 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:16:33] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 200 -
2021-03-10 13:16:35,637 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:16:35] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 200 -
2021-03-10 13:16:36,744 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:16:36] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 200 -
2021-03-10 13:16:37,769 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:16:37] "[37mPOST /api/v1/update_audio_file?audioFileType=podcast&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 200 -
2021-03-10 13:17:24,451 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:17:24,938 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:17:25,166 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:17:34,668 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:17:35,152 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:17:35,383 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:22:08,012 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:22:08,494 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:22:08,720 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:23:03,565 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:23:03] "[37mPOST /api/v1/create HTTP/1.1[0m" 200 -
2021-03-10 13:23:58,556 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:23:59,030 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:23:59,258 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:24:52,480 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:24:52,970 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:24:53,200 ERROR api: Exception on /api/v1/update_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 51, in decorated_function
    return function(*args, **kwargs)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/routes/update.py", line 46, in update_audio_file
    audioFileType = req["audioFileType"]
TypeError: 'NoneType' object is not subscriptable
2021-03-10 13:26:52,566 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:26:59,203 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:32:27,749 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:32:28,016 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:32:28,019 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:32:28,021 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:32:43,460 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:32:43,753 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:32:43,756 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:32:43,758 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:35:54,527 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:35:54,529 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:35:54,531 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:40:35,029 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:40:35,285 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:40:35,288 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:40:35,289 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:41:44,630 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:42:08,867 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:42:09,124 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:42:09,127 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:42:09,129 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:44:55,489 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:44:55,739 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:44:55,741 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:44:55,743 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:45:23,862 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:45:24,133 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:45:24,135 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:45:24,136 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:46:56,639 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:46:56,901 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:46:56,904 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:46:56,905 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:01,764 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:48:02,022 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:02,026 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:02,027 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:15,791 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:48:15] "[37mPOST /api/v1/update_audio_file?audioFileType=song&audioFileID=6046fc3b278e97c72a6633b8 HTTP/1.1[0m" 200 -
2021-03-10 13:48:47,403 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:48:47,665 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:47,667 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:48:47,669 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:50:35,308 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:50:35,536 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:50:35,539 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:50:35,541 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:50:59,627 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:50:59] "[31m[1mPOST /api/v1/delete_audio_file?audioFileType=song&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 400 -
2021-03-10 13:52:03,651 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:52:03,885 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:52:03,887 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:52:03,889 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:52:22,973 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:52:22] "[37mPOST /api/v1/delete_audio_file?audioFileType=audiobook&audioFileID=6048a221ee66022405ab6498 HTTP/1.1[0m" 200 -
2021-03-10 13:53:57,328 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:53:57,555 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:53:57,557 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:53:57,558 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:54:32,493 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:54:32] "[31m[1mPOST /api/v1/delete_audio_file?audioFileType=song&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 400 -
2021-03-10 13:55:31,517 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:55:31,749 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:55:31,751 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:55:31,752 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:56:24,168 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:56:24] "[31m[1mPOST /api/v1/delete_audio_file?audioFileType=song&audioFileID=6046fcc995184fd26e82cac1 HTTP/1.1[0m" 400 -
2021-03-10 13:56:38,119 INFO werkzeug: 127.0.0.1 - - [10/Mar/2021 13:56:38] "[37mPOST /api/v1/delete_audio_file?audioFileType=song&audioFileID=6046fc3b278e97c72a6633b8 HTTP/1.1[0m" 200 -
2021-03-10 13:57:36,234 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:57:36,466 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:57:36,469 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:57:36,470 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:57:53,937 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 13:57:54,170 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:57:54,172 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:57:54,173 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 13:59:47,663 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:00:04,752 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:00:04,986 ERROR api: Exception on /api/v1/delete_audio_file [POST]
Traceback (most recent call last):
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/utils/authentication.py", line 47, in decorated_function
    api_key = request.headers["api_key"]
  File "/Users/stephensanwo/Documents/Filed-Audio-Server/api/env/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_API_KEY'
2021-03-10 14:01:56,608 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:03:06,316 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:04:33,493 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:08:01,949 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:08:25,789 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:14:00,567 WARNING root: Unauthorized address trying to use API: 127.0.0.1
2021-03-10 14:16:42,568 WARNING root: Unauthorized address trying to use API: 127.0.0.1
